apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasks-api
  template:
    metadata:
      labels:
        app: tasks-api
    spec:
      containers:
        - name: tasks-api
          image: 29112001/tasks.api:v1.1.1
          ports:
            - containerPort: 9090
            - containerPort: 2112
          envFrom:
            - configMapRef:
                name: tasks-api
      imagePullSecrets:
        - name: regcred