apiVersion: v1
kind: Service
metadata:
  name: tasks-api
spec:
  type: LoadBalancer
  selector:
    app: tasks-api
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112