apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'tasks-api'
        scrape_interval: 10s
        static_configs:
          - targets: ['tasks-api:2112']
